### ISSUE TITLE
Ability to Pass entire contents of /plans directory to Gru

### ISSUE THREAD

**Issue by neilgroat** [smithmicro/jmeter-ecs#24]
This would be more of a feature request but having lucy pass all files from the /plans directory to gru's /plans directory would be very useful.

We have a few jmx files that will use test data that is contained in a csv file that it will read in when master launches, create specific test plans for each slave and hand them out.

With only the jmx file being provided to gru it's unable to load in the test data.

**Comment by dsperling** [comment]
That is a great idea.

**Comment by innokentiyt** [comment]
It's not enough to pass test files (e. g. CSV Data Sets) only to Gru. We need to distribute all test files to all JMeter container instances. We can do it using cycled `scp` and `ssh` commands.

Rough example:
```
# lucy.yml

version: '2'

services:
  minion:
    image: smithmicro/jmeter:latest
    mem_limit: 950m
    ports:
      - 1099:1099
      - 50000:50000
    volumes:
      - /logs:/logs
      - /plans:/plans
    environment:
      - CUSTOM_PLUGIN_URL=
```

```
# After step 5 in lucy.sh, instead "Copying $INPUT_JMX to Gru"

MINION_PUBLIC_HOSTS=$(aws ec2 describe-instances --instance-ids $MINION_INSTANCE_IDS \
      --query 'Reservations[*].Instances[*].[PublicIpAddress]' --output text | tr '\n' ' ')

echo "Copying $INPUT_JMX and all associated files to all JMeter Container EC2-Instances. Using $PEM_PATH/$KEY_NAME.pem"
echo "Copying test files to Minions..."
TEST_FILES_DIR=$(dirname $INPUT_JMX)
for DEST in $MINION_PUBLIC_HOSTS; do
  echo "Copying test files to Minion $DEST..."
  ssh -v -i $PEM_PATH/$KEY_NAME.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@${DEST} \
    "mkdir -p /tmp/testfiles"
  scp -v -i $PEM_PATH/$KEY_NAME.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $TEST_FILES_DIR/* ec2-user@${DEST}:/tmp/testfiles
  ssh -v -i $PEM_PATH/$KEY_NAME.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@${DEST} \
    "sudo cp -r /tmp/testfiles/* /plans"
done
echo "Copying test files to Gru $GRU_HOST..."
scp -v -i $PEM_PATH/$KEY_NAME.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $TEST_FILES_DIR/* ec2-user@${GRU_HOST}:/tmp
```
